### ISSUE TITLE
Visualisointi simuloinnista

### ISSUE THREAD

**Issue by Cl0wnFiesta** [Henriui/SimulaatioProjekti#9]

**Comment by rasmushy** [comment]
- Live näkymä simulaatiolle joka piirtää asetettujen parametrien mukaan oikean määrän palvelupisteitä
- Kolme palvelupistettä ylhäällä (Blender valikko -> pri- & yritysvalikko), loput piirtyy näitten alapuolelle (vasen yksityis oikea yritys)
- Ensiki pitää saada layout joka osaa piirtää oikean määrän aina palvelupisteitä oikeaan paikkaan, joku erottava tekijä näille (väri) ja saman tyypin palvelupisteillä myös otsikko (text label)
- Asiakas pallojen piirtäminen joita voi ottaa pois ja lisätä ruudulla oleviin palvelupisteisiin

//Palvelupisteet ehkä kannattaa tehdä listaan josta ne voidaan hakea jotakin vastaan (static id?, sillon 0,1,2 = blender, pri, co valikot)
